<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="ReadMPlcPackage.ReadMPlc">
    <abbreviation>
        <text>CUS</text>
     </abbreviation>
     <description>This is a ReadMPlc step.</description>
     <mil-modules></mil-modules>
     <assembly name="ReadMPlcPackage.dll"/>
     <assembly type="UI" name="ReadMPlcUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>