[default]
subheader = "5000"
network_no = "00"
pc_no = "FF"
io_no = "03FF"
station_no = "00"
monitoring_timer = "0004"
number_of_points = "0001"

[default.read]
request_length = "0018"
command = "0401"

[default.read.M]
subcommand = "0001"

[default.read.D]
subcommand = "0000"

[default.write]
request_length = "001C"
command = "1401"

[default.write.M]
subcommand = "0001"

[default.write.D]
subcommand = "0000"