<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="WriteDPlcPackage.WriteDPlc">
    <abbreviation>
        <text>CUS</text>
     </abbreviation>
     <description>This is a WriteDPlc step.</description>
     <mil-modules></mil-modules>
     <assembly name="WriteDPlcPackage.dll"/>
     <assembly type="UI" name="WriteDPlcUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>