<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="ReadDPlcPackage.ReadDPlc">
    <abbreviation>
        <text>CUS</text>
     </abbreviation>
     <description>This is a ReadDPlc step.</description>
     <mil-modules></mil-modules>
     <assembly name="ReadDPlcPackage.dll"/>
     <assembly type="UI" name="ReadDPlcUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>