<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="WriteMPlcPackage.WriteMPlc">
    <abbreviation>
        <text>CUS</text>
     </abbreviation>
     <description>This is a WriteMPlc step.</description>
     <mil-modules></mil-modules>
     <assembly name="WriteMPlcPackage.dll"/>
     <assembly type="UI" name="WriteMPlcUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>